### PR TITLE
Ft user registration 159720662

### PR DESCRIPTION
**Pull request by gtsofa**
## What does this Pull Request Do?
Registers a user and gets all users 

## Description of Task to be completed
When a user enters `username`, `email`,` password` and `confirm_password` then the user is registered into the system.

## How should this be manually tested?
- On postman , perform a POST request on `http://127.0.0.1:5000/api/v1/auth/register` 
- Enter `username`, `email`,` password` and `confirm_password` with their respective values
- Click `Send` button

### CODE REVIEW

**Comment by TheSteelGuy** [comment]
Good one just ensure  you append a new line at the end of your code

**Comment by gtsofa** [comment]
Hi @ogol254 kindly elaborate which file you're talking about because from my end I only see jsonify in line 1

**Comment by gtsofa** [comment]
@TheSteelGuy noted, thanks for the feedback

**Comment by ogol254** [comment]
check this file `app/api/v1/auth/views.py`

**Pull request merged**
